### ISSUE TITLE
Any route with "apps" gives error

### ISSUE THREAD

**Issue by destructure00** [happyleavesaoc/python-firetv#28]
Installed on a Raspberry Pi, functioning to the point where I can see two devices with http://192.168.0.110:5556/devices/list and issue media_play_pause commands successfully to both. 

Any time I run a route with "apps" on either device I either get an error or it hangs. 

Example:

devices:
  lr:
    host: 192.168.0.113:5555
  mbr:
    host: 192.168.0.117:5555

Trying to open http://192.168.0.110:5556/devices/lr/apps/running gives 

![image](https://cloud.githubusercontent.com/assets/19873190/21755512/5e33ba64-d5d2-11e6-889e-02defbb907e0.png)

sometimes it gives more information:
pi@raspi:~/python-firetv $ firetv-server -c /home/pi/python-firetv/devices.yaml
 * Running on http://0.0.0.0:5556/
('Received checksum %s != %s', (84025L, 107203))
^C----------------------------------------
Exception happened during processing of request from ('192.168.0.128', 60683)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 655, in __init__
    self.handle()
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 200, in handle
    rv = BaseHTTPRequestHandler.handle(self)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 235, in handle_one_request
    return self.run_wsgi()
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 177, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 165, in execute
    application_iter = app(environ, start_response)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/firetv/__main__.py", line 130, in running_apps
    return jsonify(running_apps=devices[device_id].running_apps())
  File "/usr/local/lib/python2.7/dist-packages/firetv/__init__.py", line 92, in running_apps
    return self._ps('u0_a')
  File "/usr/local/lib/python2.7/dist-packages/firetv/__init__.py", line 273, in _ps
    self.connect()
  File "/usr/local/lib/python2.7/dist-packages/firetv/__init__.py", line 61, in connect
    serial=self.host)
  File "/usr/local/lib/python2.7/dist-packages/adb/adb_commands.py", line 87, in ConnectDevice
    return cls.Connect(handle, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/adb/adb_commands.py", line 110, in Connect
    device_state = cls.protocol_handler.Connect(usb, banner=banner, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/adb/adb_protocol.py", line 272, in Connect
    cmd, arg0, arg1, banner = cls.Read(usb, ['CNXN', 'AUTH'])
  File "/usr/local/lib/python2.7/dist-packages/adb/adb_protocol.py", line 214, in Read
    msg = usb.BulkRead(24, timeout_ms)
  File "/usr/local/lib/python2.7/dist-packages/adb/common.py", line 303, in BulkRead
    return self._connection.recv(numbytes)
KeyboardInterrupt
----------------------------------------
192.168.0.128 - - [08/Jan/2017 18:28:11] "GET /devices/mbr/apps/running HTTP/1.1" 500 -

**Comment by happyleavesaoc** [comment]
If you have not, consider installing adb directly from the git repository. It contains bugfixes not in the pip-packaged version:

`pip install git+git://github.com/google/python-adb.git@master`

One of the fixes I believe addresses your issue.

**Comment by destructure00** [comment]
Done, now getting errors running firetv-server:

pi@raspi:~ $ firetv-server -c /home/pi/python-firetv/devices.yaml
Traceback (most recent call last):
  File "/usr/local/bin/firetv-server", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2876, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 451, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 464, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 639, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: adb>=1.1.1

**Comment by destructure00** [comment]
Turns out that installing from the git repository downgraded adb from 1.1.1 to 1.1.0. I uninstalled 1.1.0 and reinstalled 1.1.1 using pip install adb and was able to restart firetv-server. Still getting the same error as before though.

**Comment by happyleavesaoc** [comment]
Unfortunately 1.1.0 from git is actually ahead of 1.1.1 on pip. Confusing.

But anyway, I made the minimum adb version for firetv 1.1.0 so you can safely "upgrade" to the git adb version without that annoying error.

**Comment by destructure00** [comment]
"Upgraded" adb using your script command, upgraded firetv-server using 
`sudo pip install firetv[firetv-server] --upgrade`
still getting checksum error

![image](https://cloud.githubusercontent.com/assets/19873190/21876834/b2fae004-d843-11e6-925d-c132bc256557.png)
