### ISSUE TITLE
Unable to run on Alpine Linux

### ISSUE THREAD

**Issue by djdefi** [happyleavesaoc/python-firetv#3]
Running into an issue with running this on alpine linux, I found this issue: https://github.com/swig/swig/issues/344 which seems to be related, but am not quite sure the best way to address the problem in the context of this project.

```
Traceback (most recent call last):
  File "/usr/bin/firetv-server", line 7, in <module>
    from firetv.__main__ import main
  File "/usr/lib/python2.7/site-packages/firetv/__init__.py", line 11, in <module>
    from adb import adb_commands
  File "/usr/lib/python2.7/site-packages/adb/adb_commands.py", line 30, in <module>
    from M2Crypto import RSA
  File "/usr/lib/python2.7/site-packages/M2Crypto/__init__.py", line 24, in <module>
    import ASN1
  File "/usr/lib/python2.7/site-packages/M2Crypto/ASN1.py", line 12, in <module>
    import BIO
  File "/usr/lib/python2.7/site-packages/M2Crypto/BIO.py", line 221, in <module>
    class CipherStream(BIO):
  File "/usr/lib/python2.7/site-packages/M2Crypto/BIO.py", line 227, in CipherStream
    SALT_LEN = m2.PKCS5_SALT_LEN
AttributeError: 'module' object has no attribute 'PKCS5_SALT_LEN'
```

**Comment by djdefi** [comment]
FWIW, I also receive the following message when installing with `pip`:

```
pip install firetv[firetv-server]
Collecting firetv[firetv-server]
  Downloading firetv-1.0.2.tar.gz
  firetv 1.0.2 does not provide the extra 'firetv-server'
```

**Comment by happyleavesaoc** [comment]
Hmm, not sure why that is. Just tried:

```
~ > pip install firetv[firetv-server]
Downloading/unpacking firetv[firetv_server]
  Downloading firetv-1.0.2.tar.gz
  Running setup.py egg_info for package firetv
  Installing extra requirements: 'firetv_server'
  ...

~ > pip --version
pip 1.2.1 from /usr/lib/python2.6/site-packages (python 2.6)
```
