### ISSUE TITLE
Exception on /devices/default/apps/running

### ISSUE THREAD

**Issue by niklaswa** [happyleavesaoc/python-firetv#36]
```
[2017-05-02 20:15:23,874] ERROR in app: Exception on /devices/default/apps/running [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/firetv/__main__.py", line 143, in running_apps
    return jsonify(running_apps=devices[device_id].running_apps())
  File "/usr/local/lib/python2.7/dist-packages/firetv/__init__.py", line 102, in running_apps
    return self._ps('u0_a')
  File "/usr/local/lib/python2.7/dist-packages/firetv/__init__.py", line 307, in _ps
    self.connect()
  File "/usr/local/lib/python2.7/dist-packages/firetv/__init__.py", line 71, in connect
    serial=self.host)
  File "/usr/local/lib/python2.7/dist-packages/adb/adb_commands.py", line 87, in ConnectDevice
    return cls.Connect(handle, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/adb/adb_commands.py", line 110, in Connect
    device_state = cls.protocol_handler.Connect(usb, banner=banner, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/adb/adb_protocol.py", line 272, in Connect
    cmd, arg0, arg1, banner = cls.Read(usb, ['CNXN', 'AUTH'])
  File "/usr/local/lib/python2.7/dist-packages/adb/adb_protocol.py", line 215, in Read
    cmd, arg0, arg1, data_length, data_checksum = cls.Unpack(msg)
  File "/usr/local/lib/python2.7/dist-packages/adb/adb_protocol.py", line 200, in Unpack
    raise ValueError('Unable to unpack ADB command.', cls.format, message, e)
ValueError: ('Unable to unpack ADB command.', '<6I', '', error('unpack requires a string argument of length 24',))
```

**Comment by rytilahti** [comment]
This could be a bug in the underlying adb library, however, it may be worthwhile to catch and handle the exceptions separately inside python-firetv?

**Comment by rytilahti** [comment]
I have seen this happening when the device is not yet ready to receive commands. Maybe the exception should be just catched and a small warning about it displayed?

**Comment by Nazze** [comment]
Hey,

I seem to have the same issue, but with a "SIGPIPE". Seems that ADB throws a SIGPIPE after some time (I assume that just the network connectivity is broken or whatsoever) and the firetv-server stops functioning after that ( http://<<IP>>:5556/devices/list shows "Internal Server Error"), although the service as such is running. I would also be very grateful, I if the firetv-server could catch those exceptions.

KR
Nazze

**Comment by JeffLIrion** [comment]
This is an issue with the `adb` package. It should be fixed in the latest version of `firetv`, which uses a forked version of `adb`. Also, the Home Assistant component will catch these errors and automatically reconnect.
