### ISSUE TITLE
no route to host - device offline - server doesnt start

### ISSUE THREAD

**Issue by collse** [happyleavesaoc/python-firetv#38]
I have setup the server on ubuntu 16.04 and configured with persistent configuration:

service is installed via systemd

> [Unit]
Description=FireTV-Server
After=network.target
>
> [Service]
Type=simple
User=homeassistant
ExecStart=/usr/local/bin/firetv-server -c /home/homeassistant/.homeassistant/firetv_conf.yaml
>
> [Install]
WantedBy=multi-user.target

the server fails to start with the below message if any of the configured devices is offline

> Traceback (most recent call last):
  File "/usr/local/bin/firetv-server", line 11, in <module>
    load_entry_point('firetv==1.0.5', 'console_scripts', 'firetv-server')()
  File "/usr/local/lib/python2.7/dist-packages/firetv/__main__.py", line 235, in main
    _add_devices_from_config(args)
  File "/usr/local/lib/python2.7/dist-packages/firetv/__main__.py", line 224, in _add_devices_from_config
    add(device, config['devices'][device]['host'])
  File "/usr/local/lib/python2.7/dist-packages/firetv/__main__.py", line 81, in add
    devices[device_id] = FireTV(str(host))
  File "/usr/local/lib/python2.7/dist-packages/firetv/__init__.py", line 61, in __init__
    self.connect()
  File "/usr/local/lib/python2.7/dist-packages/firetv/__init__.py", line 74, in connect
    raise serr
socket.error: [Errno 113] No route to host

the configuration however states - intends are correct though not showing below

> devices:
  default: 
    host: 192.168.1.26:5555
  bedroom: 
    host: 192.168.1.27:5555

ping completes for default:

> PING 192.168.1.26 (192.168.1.26) 56(84) bytes of data.
64 bytes from 192.168.1.26: icmp_seq=1 ttl=64 time=1.31 ms
64 bytes from 192.168.1.26: icmp_seq=2 ttl=64 time=1.21 ms

**Comment by collse** [comment]
seems like if a configured device is offline the server wont start ... should have the option to only look for default and add placeholders or variables for devices that may go offline ...

**Comment by collse** [comment]
seems adding the -d option solves this issue ...
