### ISSUE TITLE
Server fails to load any firetv devices to control.

### ISSUE THREAD

**Issue by RealGandy** [happyleavesaoc/python-firetv#48]
Has been running fine, running under Python 2.7 under Ubuntu.

Since a recent restart, server only starts if it has no firetv to connect to. If started with either a default on command line or from a config file, it fails.

When trying to add a device via the api on a running server it also fails.

When adding a device via API, error message thrown is as follows:

[2018-02-10 16:23:26,917] ERROR in app: Exception on /devices/add [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/firetv/__main__.py", line 100, in add_device
    success = add(req['device_id'], req['host'])
  File "/usr/local/lib/python2.7/dist-packages/firetv/__main__.py", line 81, in add
    devices[device_id] = FireTV(str(host))
  File "/usr/local/lib/python2.7/dist-packages/firetv/__init__.py", line 61, in __init__
    self.connect()
  File "/usr/local/lib/python2.7/dist-packages/firetv/__init__.py", line 74, in connect
    raise serr
error: [Errno 104] Connection reset by peer

**Comment by JeffLIrion** [comment]
I suspect this has to do with Fire TV devices starting to require authentication. If this isn't fixed in the latest version, please reopen this issue or create a new one.
