### ISSUE TITLE
Installation on Raspberry Pi requires the flask module.

### ISSUE THREAD

**Issue by JonTheNiceGuy** [happyleavesaoc/python-firetv#5]
I have installed Raspbian Jessie, added the Home-Assistant.io "all-in-one" kit. Following that, I have done:

```
sudo adduser --system --uid 998 firetv
sudo apt install libssl-dev swig python-dev libusb-1.0-0
sudo su - firetv -s /bin/bash
virtualenv -p /usr/bin/python2.7 firetv
source firetv/bin/activate
pip install firetv[firetv-server]
```

After running the above, I get the following:

```
(firetv) firetv@homeassistant:~$ firetv-server -h
Traceback (most recent call last):
  File "/home/firetv/firetv/bin/firetv-server", line 7, in <module>
    from firetv.__main__ import main
  File "/home/firetv/firetv/local/lib/python2.7/site-packages/firetv/__main__.py", line 23, in <module>
    from flask import Flask, jsonify, request, abort
ImportError: No module named flask
```

Following a `pip install flask`, it works.

**Comment by happyleavesaoc** [comment]
I was not able to replicate this. `Flask` is listed as dependency of `firetv-server`.
