### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by derfloDev** [happyleavesaoc/python-firetv#50]
I'm using your firetv server within a homeassistant addon vor hassio (https://github.com/mpneuried/hassio-custom-addons)

starting version 3.2.4
Traceback (most recent call last):
  File "/usr/bin/firetv-server", line 11, in <module>
    load_entry_point('firetv==1.0.5', 'console_scripts', 'firetv-server')()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 561, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/site-packages/firetv/__main__.py", line 36
    def is_valid_host(host: str):
                          ^
SyntaxError: invalid syntax

**Comment by rytilahti** [comment]
This project does not support python2 (type annotations for methods are not supported there). The setup.py could be updated to add `python_requires='>=3.4'` or similar.

**Comment by ElCornelius** [comment]
This was a change some days ago:
https://github.com/happyleavesaoc/python-firetv/commit/5de43fc45c32245facb8d12121c11903bc19b421

**Comment by happyleavesaoc** [comment]
Fixed in https://github.com/happyleavesaoc/python-firetv/commit/55406c66d13a83f4be1b07e5d001dbacba19149d
