### ISSUE TITLE
load_entry_point errors

### ISSUE THREAD

**Issue by RealityX0** [happyleavesaoc/python-firetv#56]
:~$ firetv-server
Traceback (most recent call last):
  File "/usr/local/bin/firetv-server", line 9, in <module>
    load_entry_point('firetv==1.0.5', 'console_scripts', 'firetv-server')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 351, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2363, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2088, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/local/lib/python2.7/dist-packages/firetv/__main__.py", line 23, in <module>
    import yaml
ImportError: No module named yaml

Tried firetv-server -d my device address:5555 still same error message. 
pip --version = pip 1.5.4 from /usr/lib/python2.7/dist-packages (python 2.7)
Kept running install until all dependencies were met. Device is on and active. ADB works without issue. However cannot get server to run.

Thank you for any assistance.

**Comment by rytilahti** [comment]
>  ImportError: No module named yaml

Have you tried to install yaml module? pyyaml for example?

**Comment by RealityX0** [comment]
Yes. The main errors above that remain. Now it says...

:~$ firetv-server
Traceback (most recent call last):
  File "/usr/local/bin/firetv-server", line 9, in <module>
    load_entry_point('firetv==1.0.5', 'console_scripts', 'firetv-server')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 351, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2363, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2088, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/local/lib/python2.7/dist-packages/firetv/__main__.py", line 24, in <module>
    from flask import Flask, jsonify, request, abort
ImportError: No module named flask

Is not the **ImportError** unrelated to the errors preceding it?

Thank you

**Comment by rytilahti** [comment]
Yes, ImportError tells you which package or module is missing. Did you install the python-firetv with pip? It lists here flask & pyaml as dependencies: https://github.com/happyleavesaoc/python-firetv/blob/master/setup.py

**Comment by JeffLIrion** [comment]
`pip install firetv` or `pip install firetv[firetv-server]`, depending on what you want to achieve, should install all the necessary dependencies. If the error persists, please reopen this issue or create a new one.
