### ISSUE TITLE
Device authentication required, no keys available

### ISSUE THREAD

**Issue by aravorn6** [happyleavesaoc/python-firetv#68]
after update to 1.0.7 still get no connection

connection via adb command line works:

```
adb connect 192.168.1.22:5555
* daemon not running; starting now at tcp:5037
* daemon started successfully
connected to 192.168.1.22:5555
```

python3 with adb and adb-homeassistant:

```
./firetv-server -d 192.168.1.22:5555
Traceback (most recent call last):
  File "./firetv-server", line 11, in <module>
    load_entry_point('firetv==1.0.7', 'console_scripts', 'firetv-server')()
  File "/home/schlobsn/.local/lib64/python3.5/site-packages/firetv/__main__.py", line 246, in main
    if args.default and not add('default', args.default):
  File "/home/schlobsn/.local/lib64/python3.5/site-packages/firetv/__main__.py", line 89, in add
    devices[device_id] = FireTV(str(host), str(adbkey))
  File "/home/schlobsn/.local/lib64/python3.5/site-packages/firetv/__init__.py", line 106, in __init__
    self.connect()
  File "/home/schlobsn/.local/lib64/python3.5/site-packages/firetv/__init__.py", line 119, in connect
    self._adb = adb_commands.AdbCommands().ConnectDevice(**kwargs)
  File "/home/schlobsn/.local/lib64/python3.5/site-packages/adb/adb_commands.py", line 142, in ConnectDevice
    self._Connect(**kwargs)
  File "/home/schlobsn/.local/lib64/python3.5/site-packages/adb/adb_commands.py", line 173, in _Connect
    conn_str = self.protocol_handler.Connect(self._handle, banner=banner, **kwargs)
  File "/home/schlobsn/.local/lib64/python3.5/site-packages/adb/adb_protocol.py", line 318, in Connect
    'Device authentication required, no keys available.')
adb.usb_exceptions.DeviceAuthError: Device authentication required, no keys available.
```
python3 without adb and only adb-homeassistant:

```
./firetv-server -d 192.168.1.22:5555
Traceback (most recent call last):
  File "./firetv-server", line 11, in <module>
    load_entry_point('firetv==1.0.7', 'console_scripts', 'firetv-server')()
  File "/usr/lib64/python3.5/site-packages/pkg_resources/__init__.py", line 572, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib64/python3.5/site-packages/pkg_resources/__init__.py", line 2769, in load_entry_point
    return ep.load()
  File "/usr/lib64/python3.5/site-packages/pkg_resources/__init__.py", line 2422, in load
    return self.resolve()
  File "/usr/lib64/python3.5/site-packages/pkg_resources/__init__.py", line 2428, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/schlobsn/.local/lib64/python3.5/site-packages/firetv/__init__.py", line 13, in <module>
    from adb import adb_commands
ImportError: No module named 'adb'
```
python2 with adb and adb-homeassistant:

```
./firetv-server -d 192.168.1.22:5555
WARNING:root:Couldn't connect to host: 192.168.1.22:5555, error: None
 * Serving Flask app "firetv.__main__" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
```

**Comment by uchagani** [comment]
You have to generate keys.  https://www.home-assistant.io/components/media_player.firetv/#adb-authentication-for-fire-tv-devices-with-recent-software

**Comment by noahwt** [comment]
I'm having the same issue. What path do the keys need to be copied to?

**Comment by uchagani** [comment]
@noahwt create the keys on the machine that is running HA, then disconnect from adb and copy the keys to your HA config directory and use that path.

**Comment by noahwt** [comment]
Thanks for the quick reply!

I did the following after using the installation instructions on https://github.com/happyleavesaoc/python-firetv:

sudo apt-get install adb 
adb connect xxx.xxx.xxx.xxx:5555 (Fire TV)
#I copied the 2 files /home/pi/.android/adbkey and adbkey.pub to /home/homeassistant/.homeassistant/ 
sudo reboot

Do I have to do anything else to use that path?

Currently getting the following: 
pi@hassbian:~$ firetv-server -d xxx.xxx.xxx.xxx:5555 (Fire TV)
WARNING:root:Couldn't connect to host: xxx.xxx.xxx.xxx:5555, error: None
 * Serving Flask app "firetv.__main__" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off

**Comment by uchagani** [comment]
@noahwt you no longer have to manually run the firetv server.  HA will take care of it for you.  Also, in your HA config you have to specify the adb key file.  For example, if your adbkey-related files is located at `/home/homeassistant/.homeassistant/` then your config should say `/home/homeassistant/.homeassistant/adbkey`

My config looks like this:

```yaml
media_player:
  - platform: firetv
    name: Fire TV
    host: 192.168.1.88
    adbkey: /home/homeassistant/config-files/homeassistant/config/adbkey
```

Remember you must disconnect from adb after you retrieved your keys and don't run the fire tv server manually.  HA will take care of it for you.

**Comment by aravorn6** [comment]
now I got it running with the yaml config file. (I don't use homeassistant)

firetv-server -c firetv.yaml 

firetv.yaml:
```
devices:
  default:
    host: 192.168.1.22:5555
    adbkey: "/home/<user>/.android/adbkey"
```
thanks for your help
