### ISSUE TITLE
Fresh install, not working

### ISSUE THREAD

**Issue by mediamanrit** [happyleavesaoc/python-firetv#70]
Brand new install, on Raspbian.  When I run the server, it sends a traceback:

`[18:49:25] openhabian@openHABianPi:/etc/firetv$ firetv-server -d 192.168.0.80:5555

Traceback (most recent call last):
  File "/usr/local/bin/firetv-server", line 9, in <module>
    load_entry_point('firetv==1.0.7', 'console_scripts', 'firetv-server')()
  File "/usr/local/lib/python3.4/dist-packages/firetv/__main__.py", line 246, in main
    if args.default and not add('default', args.default):
  File "/usr/local/lib/python3.4/dist-packages/firetv/__main__.py", line 89, in add
    devices[device_id] = FireTV(str(host), str(adbkey))
  File "/usr/local/lib/python3.4/dist-packages/firetv/__init__.py", line 106, in __init__
    self.connect()
  File "/usr/local/lib/python3.4/dist-packages/firetv/__init__.py", line 119, in connect
    self._adb = adb_commands.AdbCommands().ConnectDevice(**kwargs)
  File "/usr/local/lib/python3.4/dist-packages/adb/adb_commands.py", line 142, in ConnectDevice
    self._Connect(**kwargs)
  File "/usr/local/lib/python3.4/dist-packages/adb/adb_commands.py", line 173, in _Connect
    conn_str = self.protocol_handler.Connect(self._handle, banner=banner, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/adb/adb_protocol.py", line 312, in Connect
    data=b'host::%s\0' % banner)
TypeError: unsupported operand type(s) for %: 'bytes' and 'bytes'
`

**Comment by mediamanrit** [comment]
FYI, this is an issue with Python 3.4 explicitly.  I ran it on Python 2.7 without issues.
